---
permalink: intro-family.html 
keywords: introduction, what E-Series is, e-series, SANtricity, CLI, system manager, unified manager 
summary: NetApp Eシリーズ製品ファミリーは、シンプルで管理が容易で、高速なブロックストレージとエンタープライズクラスの信頼性を必要とする広帯域幅アプリケーションにストレージとアプリケーションのデータ管理サービスを提供します。 
---
= Eシリーズストレージシステムの概要
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


NetApp Eシリーズストレージファミリーは、柔軟性と対費用効果に優れたクラウドへのバックアップとリカバリを提供します。シンプルで管理が容易で、エンタープライズクラスの信頼性を備えた高速なブロックストレージを必要とする、広帯域を必要とする専用アプリケーション向けに設計されています。



== Eシリーズプラットフォーム

Eシリーズストレージシステムでは、アプリケーション対応のデータ管理ツールを使用して、2Uまたは4Uフォームファクタの複数のドライブタイプに対応できます。ストレージシステムは、複数のタイプのインターフェイスからSANに接続でき、さまざまなホストオペレーティングシステムに接続できます。

Eシリーズストレージシステムには、次のプラットフォームモデルが含まれます。



=== EF600およびEF300

ビッグデータ分析やデータベースなど、最高レベルのパフォーマンスを必要とするワークロード向けに特別に設計されています。

https://docs.netapp.com/us-en/e-series/getting-started/learn-hardware-concept.html#ef600-models["EF600モデルの詳細については、こちらをご覧ください"]。

https://docs.netapp.com/us-en/e-series/getting-started/learn-hardware-concept.html#ef300-models["EF300モデルの詳細については、こちらをご覧ください"]。

https://www.netapp.com/pdf.html?item=/media/19339-DS-4082.pdf["EFシリーズのデータシートをご覧ください"^]。



=== E5700 の

ハイパフォーマンスで大量のデータを処理する帯域幅のアプリケーションをエンタープライズクラスの信頼性で運用できるように設計されています。

https://docs.netapp.com/us-en/e-series/getting-started/learn-hardware-concept.html#e5700-models["E5700モデルの詳細については、こちらをご覧ください"]。

https://www.netapp.com/pdf.html?item=/media/7572-ds-3894.pdf["E5700のデータシートをご覧ください"^]。



=== E2800

特定用途向けアプリケーションに混在ワークロードのパフォーマンスと信頼性が求められる小規模企業やリモートオフィス向けに最適化されています。

https://docs.netapp.com/us-en/e-series/getting-started/learn-hardware-concept.html#e2800-models["E2800モデルの詳細については、こちらをご覧ください"]。

https://www.netapp.com/pdf.html?item=/media/7573-ds-3805.pdf["E2800のデータシートをご覧ください"^]。



== SANtricity ソフトウェア

SANtricity ソフトウェアは、ネットワーク内のストレージシステムの表示、プロビジョニング、および管理に使用するSystem ManagerとUnified ManagerのWebベースのインターフェイスの両方を提供します。

https://www.netapp.com/pdf.html?item=/media/7676-ds-3891.pdf["SANtricity ソフトウェアのデータシートをご覧ください"^]。



=== SANtricity システムマネージャ

System Manager は Web ベースの管理ソフトウェアで、各コントローラに組み込まれています。ユーザーインターフェイスにアクセスするには、ブラウザでコントローラのIPアドレスを指定します。セットアップウィザードを使用してシステムを設定できます。

* 直感的なワークフローウィザードと状況に応じたヘルプによって、設定タスクを合理化できます。
* このソフトウェアは、高密度エンクロージャでのドロワー障害からの保護、SSDの摩耗寿命とパフォーマンスのスマートな管理など、ハードウェア機能を活用する構成候補を提案します。
* 高度なパフォーマンス監視機能により、システムレベルから個々のドライブに至るまでの情報を表示したり、パフォーマンスデータをエクスポートして詳細な分析を行うことができます。
* SSDキャッシュやデータキャッシュの管理などの調整作業はすべてオンラインです。修復が必要になった場合は、SANtricity Recovery Guruにステップバイステップの手順が記載されます。


にアクセスします https://docs.netapp.com/us-en/e-series-santricity/system-manager/index.html["SANtricity システムマネージャのドキュメントサイト"]では、ストレージアレイの計画、設定、管理、トラブルシューティングに関する情報を参照できます。



=== SANtricity Unified Manager の略

Unified Manager は、ドメイン全体の管理に使用する Web ベースのソフトウェアです。E2800 、 EF280 、 EF300 、 E5700 、 EF570 など、すべての新しい E シリーズおよび EF シリーズアレイのステータスをまとめて表示できます。 および EF600 ：選択したストレージアレイに対してバッチ処理を実行することもできます。

* 1つのウィンドウで、ステータスの表示、アレイのグループ化、複数のアレイのSANtricity OSの更新、各アレイの組み込みのSANtricity システムマネージャの起動を行うことができます。
* 1回の操作で複数のアレイにアラートやその他の設定を簡単に行うことができます。
* SANtricity Unified Managerは、LinuxまたはWindowsの管理サーバにインストールされ、ブラウザで実行されます。


にアクセスします https://docs.netapp.com/us-en/e-series-santricity/unified-manager/index.html["SANtricity Unified Managerドキュメントサイト"]では、複数のネットワークストレージアレイでストレージ管理コマンドを実行する方法について説明します。



=== SANtricity Web Services Proxy の略

Web Services Proxyは、オーケストレーションと自動化のニーズに対応するフル機能のRESTful APIサーバで、数百台規模の新旧のEシリーズアレイを管理できます。Windows サーバまたは Linux サーバに別途インストールされます。Web Services には、 REST API と直接やり取りできる API ドキュメントが含まれています。

にアクセスします https://docs.netapp.com/us-en/e-series/web-services-proxy/index.html["Web Services Proxyのドキュメント"]。



== CLI の使用

コマンドラインインターフェイス（ CLI ）は、ストレージアレイを設定および監視するためのソフトウェアアプリケーションです。

CLI を使用すると、 DOS の C ：プロンプト、 Linux のオペレーティングシステムパス、 Solaris のオペレーティングシステムパスなど、オペレーティングシステムのプロンプトからコマンドを実行できます。

にアクセスします https://docs.netapp.com/us-en/e-series-cli/index.html["SANtricity CLIドキュメントサイト"]では、CLIコマンドを使用してストレージアレイを設定および監視する方法を確認できます。



== を参照してください。

* https://docs.netapp.com/us-en/e-series/index.html["Eシリーズシステムのドキュメント"^]
* https://docs.netapp.com/us-en/e-series-santricity/index.html["SANtricity ソフトウェアのドキュメント"^]
* https://docs.netapp.com/us-en/e-series-cli/index.html["SANtricity CLIのドキュメント"^]

