---
settings:
  name: E-Series Family
  search: e-series,e-series-santricity,e-series-cli
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Eシリーズ製品ファミリーのドキュメント
    url: "/index.html"
product-family:
  sidebarlinks:
  - title: すべて
    tags: tag_storage_management, tag_data_storage, tag_cli, tag_get_started, tag_SANtricity,
      tag_solution
    class: active
  - title: はじめに
    tags: tag_get_started
  - title: データストレージ
    tags: tag_data_storage
  - title: ストレージ管理
    tags: tag_storage_management, tag_SANtricity
  - title: 解決策
    tags: tag_solution
  tiles:
  - title: Eシリーズの詳細をご確認ください
    icon: "./media/groups_line-1.png"
    url: intro-family.html
    summary: Eシリーズファミリーのストレージシステムについて説明します。
    tags: all, tag_get_started
  - title: Eシリーズシステム
    icon: "./media/system_line.png"
    url: "../e-series/index.html"
    summary: Eシリーズストレージシステムは、高速なブロックストレージとエンタープライズクラスの信頼性でアプリケーションワークロードをサポートします。
    tags: all, tag_data_storage
  - title: SANtricity ソフトウェア
    icon: "./media/config_line.png"
    url: "../e-series-santricity/index.html"
    summary: SANtricity ソフトウェアを使用して、WebベースのインターフェイスからEシリーズストレージシステムをプロビジョニングおよび管理します。
    tags: all, tag_storage_management, tag_SANtricity
  - title: コマンドラインインターフェイス
    icon: "./media/cli_line.png"
    url: "../e-series-cli/index.html"
    summary: CLIを使用して、オペレーティングシステムのプロンプトからEシリーズストレージシステムを設定および監視します。
    tags: all, tag_storage_management, tag_SANtricity
  - title: WebサービスAPI
    icon: "./media/api.png"
    url: "../e-series/web-services-proxy/index.html"
    summary: RESTful APIを使用して、新旧のEシリーズストレージシステムのワークフローを構築、自動化できます。
    tags: all, tag_storage_management, tag_SANtricity
  - title: Eシリーズストレージを使用したネットアップのBeeGFS
    icon: "./media/api.png"
    url: "../beegfs/index.html"
    summary: BeeGFSをネットアップで使用して、BeeGFS並列ファイルシステムとNetApp EF600ストレージシステムを組み合わせた高可用性インフラを構築して導入します。
    tags: all, tag_solution
